version: '2.1'
orbs:
  node: circleci/node@5.2.0
  helm: circleci/helm@3.0.2
jobs:
  react_test_build:
    parameters:
      org_name:
        description: Name of the organization
        type: string
      app_name:
        description: Name of the application
        type: string
      app_version:
        description: Version of the application
        type: string
    docker:
      image: cimg/node:20.12.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: "npm"
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist
          destination: << parameters.app_name >>-<< parameters.app_version >>
workflows:
  deployment:
    jobs:
      - react_test_build:
          org_name: topfilms
          app_name: primary-ui
          app_version: 1.0.0