version: '2.1'
orbs:
  node: circleci/node@5.2.0
jobs:
  react_test_build:
    parameters:
      app_name:
        description: Name of the application
        type: string

      app_version:
        description: Version of the application
        type: string

    docker:
      - image: cimg/node:20.12.0

    steps:
      - checkout

      - node/install-packages:
          pkg-manager: 'npm'

      - run:
          name: Run tests
          command: npm run test

      - run:
          name: Build
          command: npm run build

      - persist_to_workspace:
          root: dist
          paths: "*"

      - store_artifacts:
          path: dist
          destination: << parameters.app_name >>-<< parameters.app_version >>

  docker_artifact_build_push:
    parameters:
      org_name:
        description: Name of the organization
        type: string

      app_name:
        description: Name of the application
        type: string

      app_version:
        description: Version of the application
        type: string

    docker:
      - image: cimg/base
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

    steps:
      - attach_workspace:
          at: /dist

      - run:
          name: Build and tag Docker image
          command: |
            docker buildx build --platform linux/arm64/v8 . -t $DOCKER_USERNAME/<< parameters.org_name >>-<< parameters.app_name >>:<< parameters.app_version >>

      - run:
          name: Push Docker image
          command: |
            $DOCKER_USERNAME/<< parameters.org_name >>-<< parameters.app_name >>:<< parameters.app_version >>

workflows:
  deployment:
    jobs:
      - react_test_build:
          app_name: primary-ui
          app_version: 1.0.0
          context:
            - secrets
      - docker_artifact_build_push:
          org_name: topfilms
          app_name: primary-ui
          app_version: 1.0.0
          context:
            - secrets
          requires:
            - react_test_build
