image:
  repository: maxmorhardt/topfilms-primary-ui
  tag: '1.0.0'
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: topfilms.co
      paths:
        - path: /
          pathType: Prefix
  tls: 
   - secretName: topfilms.co-cert
     hosts:
       - topfilms.co

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi